[tool.aliases]
test = "pytest"

[tool.pytest]
addopts = [
    "--ignore=fire/test_components_py3.py",
    "--ignore=fire/parser_fuzz_test.py"
]

[tool.pytype]
inputs = "."
output = ".pytype"

[tool.ruff]
# Enable specific rule categories
select = ["E", "F", "W", "C90"]

# Exclude specific files and directories
exclude = ["build", "dist", ".venv"]

# Set the maximum line length
line-length = 80

# Enable autofix for certain rules
fixable = ["E", "F", "W", "C90"]

# Specify additional settings for specific rules
[tool.ruff.per-file-ignores]
"tests/*" = ["D", "E"]